### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by tapio-salonen** [Mvaaras/improved-notes-webapp#3]
# Vertaisarviointi

Tulee vähän myöhässä tämä vertaisarviointi, mutta halusin siitä huolimatta tehdä sen.

Sovelluksella vaikuttaa olevan toimiva pohja ja käyttäjän pyyntöihin vastataan responsiivisesti. Koodi on hyvin jaoiteltu omiin moduuleihinsa ja lukijalle on selvää mitä mikäkin moduuli tekee.

Huomioita sovelluksesta:
* Uuden käyttäjän luonnin yhteydessä ei ole tällä hetkellä validointia. Voisi olla järkevää, että esimerkiksi käyttäjätunnuksella ja salasanalla olisi jokin minimipituus.
* Kirjautumisen epäonnistuessa voisi esittää syyn siitä miksi kirjatuminen epäonnistuu, esim väärä "väärä käyttäjätunnus tai salasana", tämä sama pätee uuden käyttäjän luontiin.
* Muistiinpanon luonti näkymässä voisi olla return nappula jos käyttäjä ei haluakkaan luoda uutta muistiinpanoa.

Huomioita koodista:
* HTML tiedostoilla voisi olla yhteinen layout ja täten eri sivut perisivät saman rakenteen toisten sivujen kanssa.
* Itselle hämmennystä aiheutti muistiinpanon poisto toiminnallisuus. Käytännössähän tämä ei poista poistettavaa muistiinpanoa, vaan tekee sen vain näkymättömäksi. Voisiko tämän ehkä nimetä toisin, että metodin toiminta kuvaisi sitä mitä se oikeasti tekee. Lisäksi merkitys visibility arvoille (pelkän yhden kirjaimen perusteella) jää hieman "pääteltäväksi".
* Koodissa näyttäisi olevan CSRF haavoittuvuus, tosin tämän voi korjata myöhemminkin.
* Koodi on selkeää, tiivistä, hyvin jaoiteltua ja ei ole selkeää copy pastea, hienoa!

**Comment by Mvaaras** [comment]
Kiitoksia vertaisarvioinnista! Otan saamani kommentit huomioon jatkon kannalta :)
