### ISSUE TITLE
Kurssin vertaisarviointi (tietokantasovellus)

### ISSUE THREAD

**Issue by federma** [Mvaaras/improved-notes-webapp#5]
Vertaisarviointi (tietokantasovellus -kurssin harjoitustyö)

# Käytettävyys

* Pääpiirteittäin sovelluksen toiminnot tuntuvat toimivan oikein
* Linkit toimii, mutta niitä voisi olla enemmän (esim. rekisteröinti sivulta ei ole linkkiä pois, jos ei haluakaan luoda tunnusta) tai navigointivalikko
* Lomakkeissa ei ole ilmeisesti juurikaan validointeja -> pystyy esim. rekisteröimään uuden käyttäjän ilman nimeä ja salasanaa
* Virheilmoitukset näkyy eri sivulla (esim. "login failed"), eikä virhesivulta ole linkkiä minnekään
* Olisiko hyvä luoda valmiit tagi -kategoria, joista voisi valita muistiinpanoon sopivat? Nyt jos on esim. kirjoitusasussa eroa, niin lajittelu tagin mukaan ei toimi kovin. Jos siis esim. toisessa on tagina "oma" ja toisessa "omat", niin menevät eri kategorioihin. Jos siis olisi vaikka valmiit "työ", "opiskelu", "harrastuksen" jne. tagit ja käyttäjä valitsisi itselleen sopivan
* Laitoin testiksi peräkkäin kaksi notea, joissa sama sisältä (molemmissa teksti "sama" notena ja tagina). Toinen näistä tallentui ilman tagia ja ensimmäiseen tuli tuplana tagiksi "sama". Bugi?
* Kun klikkaa kertaalleen tagia, niin lajittelu toimii, mutta jos ikkunassa "vieming tag" klikkaan uudeelleen tagia, niin linkki ohjaa sivulle, jota ei ole olemassa. Esim. jos tagi on "perus" niin URL on .../tag/perus ja sieltä klikatessa URL:iksi tulee .../tag/tag/perus -> eli tässä on ohjaus pielessä
* Luodun noten tagia olisi kiva voida muokata - tämä sinulla taisikin olla mielessä vielä tuoda sovellukseen
* Toimintoja on toistaiseksi aika vähän, mutta perusidea on minusta potentiaalinen ja oikein kehityskelpoinen

# Koodi

* Koodia on siistiä ja selkeää
* Tietokannan taulut on järjestelty mielekkäästi, mietin vain onko tagged taulussa hyvä viitata käyttäjiin - eikö tag ole enemmän noten ominaisuus?
* Ehkä myös note:issa voisi olla luontiaika tallennettu tietokantaan?

Hyvää pohjatyötä! Tsempppiä projektin loppuvaiheeseen!

**Comment by Mvaaras** [comment]
Kiitos palautteesta :)
